version: '3.7'

services:
    spigot:
        build:
            context: ./.docker/spigot
            dockerfile: Dockerfile
            args:
                version: 1.8.8
        container_name: spigot
        environment:
            MC_RAM_MIN: 2G
            MC_RAM_MAX: 4G
        ports:
            - 25565:25565
        volumes:
            - ./minecraft/plugins/:/home/minecraft/plugins/
            - ./minecraft/logs/latest.log:/home/minecraft/logs/latest.log
        tty: true
        stdin_open: true